### ISSUE TITLE
thor: Show stack traces on kernel panic

### ISSUE THREAD

**Issue by avdgrinten** [managarm/managarm#107]
Add the option to compile the kernel with `-fno-omit-frame-pointer` and print a stack trace on panics.

**Comment by avdgrinten** [comment]
This issue would help to debug certain issues on real hardware that we discussed in Discord yesterday.

CC @qookei.

**Comment by qookei** [comment]
Wasn't this fixed by 13ddd68c3bbc680e044466e0ade4cc6590b4f059?

**Comment by avdgrinten** [comment]
True, this issue can be closed.
