### ISSUE TITLE
eir: Support modules in high memory

### ISSUE THREAD

**Issue by avdgrinten** [managarm/managarm#124]
Right now, eir discards all memory between `0x100000` and the highest address of any module from the memory map. This makes sense on BIOS systems but does not work well on UEFI, where the boot loader cannot easily control the placement of modules.

**Comment by qookei** [comment]
Fixed by b8b8489511ad12902d9598511389f421026327e1 for multiboot1, 59d8d1f215198f910271ebdd23a0589ee1e4a8e1 for multiboot2, 883307f1580e3f6f69a18e3f72d51d8c59bf61c2 for stivale2.
