### ISSUE TITLE
thor: Take ACPI RSDP from eir

### ISSUE THREAD

**Issue by avdgrinten** [managarm/managarm#125]
Currently, thor searches for the RSDP in low memory. Let eir do that work on platforms where it makes sense.

**Comment by qookei** [comment]
This is already solved (764ef7c47d281aa11ab8327c0e739b1ef392e497 for MB2 and d02f4cf2e749fd4fe5e7e99cf18878e9b585089e for stivale).

**Comment by avdgrinten** [comment]
Well, for these protocols, it is indeed already solved but we also need to solve it for MB1, which requires searching for the RSDP in Eir.
