### ISSUE TITLE
problem with xbstrap

### ISSUE THREAD

**Issue by mnisk** [managarm/managarm#129]
I have installed the xbstrap tool from the python3 pip and installed but when I execute it shows the following error:-
TypeError: namedtuple() got an unexpected keyword argument 'defaults'
the complete error is in the screen shot below=
![Screenshot (814)](https://user-images.githubusercontent.com/49841018/77821277-e1343f80-710e-11ea-997d-e3118af50d05.png)

**Comment by avdgrinten** [comment]
This is related to the Python version. We are making use of a Python 2.7 feature there which can probably be avoided...

**Comment by mnisk** [comment]
any solution regarding it

**Comment by avdgrinten** [comment]
For clarification: do you try to use xbstrap to build managarm or to build some other OS?

For Managram, one solution is to use the docker container that we provide.

**Comment by avdgrinten** [comment]
This is fixed on the `master` branch of xbstrap.
