### ISSUE TITLE
posix: crash when trying to open a symlink

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/managarm#132]
posix-subsystem panics when trying to do nano /etc/localtime, which is a symlink.
Opening the file that the symlink points to works fine.
The error messages shown can be found [here](https://pastebin.com/y5NAGzX7).

**Comment by avdgrinten** [comment]
Thank you for the report. I suspect that this happens if a symlink is opened with `O_NONFOLLOW` but we have to investigate more to be sure.

**Comment by Dennisbonke** [comment]
This has been fixed in the meantime.
