### ISSUE TITLE
port: tar -z does not work

### ISSUE THREAD

**Issue by avdgrinten** [managarm/managarm#138]
gzip and tar individually work fine but commands like `tar -xzf <file>` fail.

**Comment by avdgrinten** [comment]
This might be due to an incorrect `fcntl(F_GETF)` implementation. To fix this, pass the open mode (i.e., one of: ro, wo, rw) through extern_fs to libblockfs and return it correctly.

**Comment by Dennisbonke** [comment]
This issue has been fixed in the meantime
