### ISSUE TITLE
mbus: Redesign object creation

### ISSUE THREAD

**Issue by avdgrinten** [managarm/managarm#158]
mbus works reasonably well but after a few years of usage, some design limitations become apparent. This issue is part of a redesign of mbus.

Regarding **object creation**, mbus has a few issues:
* Objects are arranged in a hierarchical tree but this feature it not used by anywhere in Managarm. Instead, objects should reside in a single global flat (i.e., non-hierarchical) collection.
* On `BIND`, mbus queries the object's owner for a descriptor (such as a stream). This opens up a denial-of-service vector against the mbus server: object owners can just refuse to ever respond to that request. Instead, a single descriptor should be passed to mbus during object creation. More generally, mbus should be redesigned so that it *never* requests anything from a client.
* This change will also remove all callbacks that the current client-side library uses. (These callbacks are tedious to deal with in an asynchronous environment.)
* Objects should be associated with two streams: one stream held by the object owner and one stream passed to clients that enumerate the object. When the owner closes its stream, the object should be destroyed.

To implement this new design, we should add a `CREATE_OBJECT_NG` request, migrate existing code to `CREATE_OBJECT_NG` and then delete `CREATE_OBJECT` in favor of `CREATE_OBJECT_NG`.

**Comment by cflaviu** [comment]
I understanding mbus provides a server discovery service and a communication service and discovery service is based on protobuffers. Is it that correct? I'm not sure what is used behind communication service.

**Comment by avdgrinten** [comment]
Yes, the mbus protocol itself (= the one that contains the CREATE_OBJECT and BIND requests) is based on protobuf.

The communication protocol over the IPC stream that the BIND request returns to the client is *not* specified by mbus. mbus just establishes the communication channel but does not demand any particular protocol.

**Comment by cflaviu** [comment]
Ok, thanks. A list of groups containing only objects or just a list of objects is the intent?

**Comment by avdgrinten** [comment]
As mentioned on Discord, the groups feature will eventually be removed.
