### ISSUE TITLE
g++ crashes due to missing support of partial munmap()

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/managarm#162]
When running the following command `g++ -o test-g++ test-g++.cpp`, the following error is triggered:
```
In function unmapFile, file ../../../src/managarm/posix/subsystem/src/process.cpp:189: Assertion 'i
 != _areaTree.end()' failed!
In function abort, file ../../../src/mlibc/options/ansi/generic/stdlib-stubs.cpp:213
__ensure(!"Not implemented") failed
thor: Panic in server sbin/posix-subsystem
```

**Comment by Dennisbonke** [comment]
This can also be triggered by running `gcc` enough times

**Comment by Geertiebear** [comment]
Does this still happen?

**Comment by Dennisbonke** [comment]
I’ll check that in the afternoon, it might’ve been fixed by recent fixes

**Comment by Dennisbonke** [comment]
This seems to be fixed, g++ now complains about a different issue, I'll open a new issue for that.
