### ISSUE TITLE
thor: Panic on boot after lockRange() failure

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/managarm#171]
While booting, the following is printed in the kernel log
```
POSIX: Installing block device sda0
unix device: Connection
init: Mounting /dev/sda0
mlibc: mkdir() ignores its mode
init: On /realfs
Panic!
Assertion failed: !"lockRange() failed"
In function copyFromBundle at ../../../src/managarm/kernel/thor/generic/memory-view.cpp:422
```

Attached is the [stacktrace](https://github.com/managarm/managarm/files/4663842/message.txt)

**Comment by Geertiebear** [comment]
Does this still happen?

**Comment by Dennisbonke** [comment]
I haven't seen this issue in a long time. I'm fine with calling it fixed if no one has any objections to that.

**Comment by qookei** [comment]
The function this happened in does not exist anymore, and IIRC it was due to a copy-paste mistake resulting in the use of the wrong node type to complete the async operation. Make a new issue if this crops up again.
