### ISSUE TITLE
thor: Boot failure due to ACPI error

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/managarm#205]
When trying to boot managarm on real hardware, I got the following error
![noacpi](https://user-images.githubusercontent.com/8709509/89034293-f4fbe680-d338-11ea-92a9-318e69b1256e.jpg)

This was produced on a laptop with an intel i7-8750H, on a NL5C motherboard (manufacturer Quanta)

**Comment by Dennisbonke** [comment]
Some progress has been made, but the possible fix is stuck in testing until qword-os/lai#87 is resolved

**Comment by avdgrinten** [comment]
Does thor detect ACPI now? If yes, we can close this and track progress in the LAI issue.

**Comment by Dennisbonke** [comment]
Yes, acpi seems to be detected iirc. I'll retest that soon and close this issue if it is.

**Comment by avdgrinten** [comment]
Closing this since it is solved.
