### ISSUE TITLE
`weston-desktop` image built with xbstrap fails to start weston

### ISSUE THREAD

**Issue by KSPAtlas** [managarm/managarm#423]
So, after following the instructions in the Handbook and building Managarm, attempting to start it with `xbstrap run qemu` causes a userspace panic:

```
Could not satisfy dependency libffi.so.7
posix: User space panic in process /usr/bin/weston
rax: 0000000000000028, rbx: ffffe0000552d8c0, rcx: 0000000000000000
rdx: 000000000000000d, rdi: 000000000000000a, rsi: 000000004001ee06
 r8: 0000000000000000,  r9: 0000000000000040, r10: 0000000000000049
r11: 0000000000000000, r12: 000000004140277f, r13: 0000000040226520
r14: 00007fffffdbf600, r15: 0000000000000010, rbp: 00007ffffffff730
rip: 0000000040000601, rsp: 00007ffffffff728
Mappings:
0000000000400000 - 000000000040d000 P xr- /usr/bin/weston + 0x0
000000000060d000 - 000000000060e000 P -rw /usr/bin/weston + 0x0
0000000040000000 - 0000000040026000 P xr- /usr/lib/ld.so + 0x0
               ^ IP is 0x601 bytes into this mapping
0000000040226000 - 0000000040227000 P -rw /usr/lib/ld.so + 0x0
0000000041000000 - 0000000041032000 P xr- /usr/lib/libweston-4.so.0.0.0 + 0x0
0000000041231000 - 0000000041234000 P -rw /usr/lib/libweston-4.so.0.0.0 + 0x31000
0000000041400000 - 0000000041411000 P xr- /usr/lib/libwayland-server.so.0.1.0 + 0x0
0000000041611000 - 0000000041613000 P -rw /usr/lib/libwayland-server.so.0.1.0 + 0x11000
00007fffffa7b000 - 00007fffffafb000 P -rw anon + 0x0
00007fffffafd000 - 00007fffffb7d000 P -rw anon + 0x0
00007fffffb7d000 - 00007fffffbfd000 P -rw anon + 0x0
00007fffffbfd000 - 00007fffffc7d000 P -rw anon + 0x0
00007fffffc7d000 - 00007fffffcfd000 P -rw anon + 0x0
00007fffffcfd000 - 00007fffffd7d000 P -rw anon + 0x0
00007fffffd7d000 - 00007fffffdfd000 P -rw anon + 0x0
00007fffffe00000 - 0000800000000000 P -rw anon + 0x0
               ^ Stack is 0x1ff728 bytes into this mapping
posix: Thread killed as the result of signal 6
init: Launched process terminated
```

Where is libffi? Is it in a package because if so, it needs to be in weston-desktop

**Comment by Dennisbonke** [comment]
Can you verify that libffi.so.* doesn’t exist in the image? Just wanting to rule out libffi.so.6 existing and 7 requested. Also, are you using cbuildrt as mentioned in the handbook or are you using one of the alternative ways of building?

**Comment by KSPAtlas** [comment]
> Can you verify that libffi.so.* doesn’t exist in the image? Just wanting to rule out libffi.so.6 existing and 7 requested. Also, are you using cbuildrt as mentioned in the handbook or are you using one of the alternative ways of building?

I am using cbuildrt, but I don't know how to check the image

**Comment by Dennisbonke** [comment]
Just check in `system-root/usr/lib/` and friends. Also one could check `packages/libffi/usr/lib/` and friends.

**Comment by KSPAtlas** [comment]
> Just check in `system-root/usr/lib/` and friends. Also one could check `packages/libffi/usr/lib/` and friends.

There is no libffi in sysroot or packages

**Comment by Dennisbonke** [comment]
Interesting. It _should_ be installed as part of the `base` metapackage. If you mount the image, and look in `/etc/xbstrap`, is there a `libffi.installed` there?

**Comment by KSPAtlas** [comment]
Apparently after installing libffi manually, there is no libffi.so.7

**Comment by Dennisbonke** [comment]
I think I figured it out, because I only have `libffi.so.8` myself too. A rebuild of weston on our ci should fix the broken dependency, and as we just upgraded weston, this is happening basically as we speak. You can upgrade weston hopefully later today (CET timezone). Paging @ArsenArsen as I believe that managarm/xbbs#6 would've caught this no? I'll leave this issue open for now pending the build fix on the ci.

**Comment by ArsenArsen** [comment]
this is a missing revdep revision bump? a shlib db would've caught this

**Comment by Dennisbonke** [comment]
Yep sure looks like it, but unless I'm stupid, this would _also_ be caught by the issue linked above right? Surely linking against different library versions would produce different packages.

**Comment by Dennisbonke** [comment]
This should be fixed now, can you update your local Weston and try again?

**Comment by KSPAtlas** [comment]
Forgot to close but it works
