### ISSUE TITLE
posix: Unhandled page fault on invoking node.js

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/managarm#426]
When invoking node with a small test script (provided below) posix-subsystem will crash after the script is finished with an unhandled page fault.

e9 log
```
thor: Unhandled page fault at 0x20, faulting ip: 0x47edcd
thor: Page fault at 0x20, faulting ip: 0x47edcd
Errors: (User) (Page not present) (Read)
thor: Page fault in server, at 0x20, faulting ip: 0x47edcd
thor: Fault in server sbin/posix-subsystem
```

A backtrace can be found [here](https://really.bad-me.me/Aed2ZVs.log). The offending line seems to be [this one](https://github.com/managarm/managarm/blob/5e6173abb2f2b1c365e6774074380255bcccf3a5/posix/subsystem/src/fifo.cpp#L114).

Test script
```js
console.log('Hello Managarm world!')
```

**Comment by no92** [comment]
Solved by #549.
