### ISSUE TITLE
Add parsing of kernel and init arguments for debugging and changing functionality

### ISSUE THREAD

**Issue by qookei** [managarm/managarm#466]
This would include for example:
 - specifying the root partition,
 - disabling certain block device drivers to avoid them becoming `/dev/sda` (stop-gap measure to help with #322),
 - disabling functionality causing problems (broken CPU features, etc.),
 - forcing functionality to be enabled even if not detected (device quirks, misreported features, etc.),
 - enabling debugging options (extra prints or error checking).

The parser for this would most likely live in frigg. Proposed format is: `opt1 opt2 opt3=value group1=opt4,opt5`

**Comment by qookei** [comment]
See managarm/frigg#62 for the parser implementation.

**Comment by avdgrinten** [comment]
This has been fixed in the meantime.
