### ISSUE TITLE
Issue when booting via qemu

### ISSUE THREAD

**Issue by rayanmargham** [managarm/managarm#467]
![image](https://user-images.githubusercontent.com/69608259/174871596-241ad031-89dd-45a4-ae2a-c71657da2db9.png)
Yea here, not sure why but it just doesn't wanna boot

sorry for not providing a lot of info I'm doing this on behalf of my friend and he isn't providing a lot of info

**Comment by ArsenArsen** [comment]
What exact QEMU command is being ran? Also, I propose joining us in some live communication channel so that we can bounce ideas back and forth.

**Comment by rayanmargham** [comment]
I'm asking my friend for the qemu command rn and I'm in the osdev discord we can communicate through there?

**Comment by ArsenArsen** [comment]
Please join the managarm Discord server, it's linked in the README.

**Comment by rayanmargham** [comment]
alright

**Comment by rayanmargham** [comment]
which channel should we talk in?

**Comment by 64** [comment]
general or managarm-dev is fine

**Comment by rayanmargham** [comment]
alright see you there
