### ISSUE TITLE
is there a plan to support linux device drivers as well 

### ISSUE THREAD

**Issue by RavikumarTulugu** [managarm/managarm#501]
Are there any plans to support linux device drivers as well ? it would be great to have it .

**Comment by Dennisbonke** [comment]
Not directly, supporting all internal kernel interfaces is quite likely not going to happen. However, supporting all devices that Linux supports, while it is a massive undertaking, people are free to work on that of course.

**Comment by 64** [comment]
Indeed, the internal Linux kernel APIs would be extremely difficult to support.
