### ISSUE TITLE
Define a clang-format file

### ISSUE THREAD

**Issue by cflaviu** [managarm/managarm#527]
A standardized coding style would make the life easier to contributors.
[An online configuration tool ](https://clang-format-configurator.site/)could be used to define such coding style file.

**Comment by Dennisbonke** [comment]
It's in the works, I expect one in the coming weeks. I have it ready but it's blocked on llvm 16, which I'll PR in tomorrow hopefully.

**Comment by ArsenArsen** [comment]
https://github.com/ArsenArsen/managarm/blob/clang-reformat/.clang-format

**Comment by Dennisbonke** [comment]
I did some testing and some small tweaks. Also enabled some options that are only in llvm 15 or above, hence the llvm upgrade

**Comment by cflaviu** [comment]
Most Linux distributions do not provide the latest clang-format version, v16. 
It would be more useful to target version v14 or v15 to cover a broader range of users. In my case I have by default v14 but I can install v15, but not v16.
clang-format doesn't offer enough configuration granularity to describe a specific coding style and it is expected to make some compromises regarding the formatting, eg. in my particular case, the initialization lists. IMO it's not worth finding the perfect tool to match the expected coding style.

**Comment by ArsenArsen** [comment]
you can use host-llvm-toolchain to run clang-format

**Comment by Dennisbonke** [comment]
See #528

**Comment by avdgrinten** [comment]
This is implemented now.
