### ISSUE TITLE
general: Boot fails in UTC timezone (was: keeping showing waiting for /dev/sda0)

### ISSUE THREAD

**Issue by Manish-Kala-Jaat** [managarm/managarm#80]
during the boot process it keep showing the message:-
waiting for /dev/sda0
screenshot:-
![Screenshot from 2019-05-17 12-43-40](https://user-images.githubusercontent.com/49841018/57909815-6faa2480-78a1-11e9-9a08-52073352a769.png)

**Comment by avdgrinten** [comment]
Thank you for the report.

Did you use the `run-qemu` script from bootstrap-managarm? If yes, could you post the console log to a pastebin (or similar) and link it?

**Comment by Manish-Kala-Jaat** [comment]
No , I that script is giving error for no kvm something like that .
Instead I used =
qemu-system-x86_64 -hda image -m 1024

**Comment by avdgrinten** [comment]
If you don't have KVM, you could comment out `-enable-kvm` from the script. Note that qemu without KVM is quite a bit slower than KVM.

If you do not want to use the script, attaching the image to a virtio-block device should work. To do this, pass `-drive id=hdd,file=image,format=raw,if=none -device virtio-blk-pci,drive=hdd` to qemu.

I would also suggest to pass `-device piix3-usb-uhci -device usb-kbd -device usb-tablet` as the USB tablet emulation does not require mouse grab.

**Comment by Manish-Kala-Jaat** [comment]
that worked but more problems is encountered :-
![Screenshot from 2019-05-17 12-48-37](https://user-images.githubusercontent.com/49841018/57912115-26f56a00-78a7-11e9-90e9-c902f089a8c9.png)

**Comment by Manish-Kala-Jaat** [comment]
the complete log is available here=
https://pastebin.com/c06EC9Di

**Comment by avdgrinten** [comment]
This is indeed a bug in mlibc that occurs in timezones with constant offset to UTC. I will prepare a fix.

**Comment by avdgrinten** [comment]
I pushed a fix to mlibc. In your source `mlibc/` directory, you should be able to pull from `https://github.com/managarm/mlibc.git`. You can rebuild the library using `xbstrap install --rebuild mlibc` (in your build directory). Afterwards, you can rerun `mkimage` and qemu.

**Comment by Manish-Kala-Jaat** [comment]
so it goes to next step and shows desktop but does nothing , also shows some error in log :-
screenshots=
![Screenshot from 2019-05-18 14-03-49](https://user-images.githubusercontent.com/49841018/57966961-8e2e1f80-7976-11e9-9eb8-9193c0de2757.png)

![Screenshot from 2019-05-18 14-04-20](https://user-images.githubusercontent.com/49841018/57966969-99814b00-7976-11e9-89c6-dc505ecf6caa.png)

complete log file at=
https://pastebin.com/b5xqjS4x

**Comment by avdgrinten** [comment]
Thank you for the report. I opened #81 and will try to reproduce and fix this problem.

**Comment by Manish-Kala-Jaat** [comment]
okay now I just build it from starting now got new errors.

![Screenshot from 2019-05-21 11-32-09](https://user-images.githubusercontent.com/49841018/58072091-400a5d80-7bbc-11e9-9949-d9996bbee4b8.png)

FULL LOG AT=
https://pastebin.com/Ht4V77r2
