### ISSUE TITLE
gfx/plainfb: Driver fails due to missing ioctl()

### ISSUE THREAD

**Issue by avdgrinten** [managarm/managarm#81]
Log at https://pastebin.com/b5xqjS4x

_Originally posted by @Manish-Kala-Jaat in https://github.com/managarm/managarm/issues/80#issuecomment-493659888_

**Comment by avdgrinten** [comment]
@Manish-Kala-Jaat could you check whether your `managarm` repo in `<source-dir>/managarm/` is up to date? If not, please pull the current version and rebuild it using `xbstrap install --rebuild managarm-system`.

If it is already up to date, it might be worth trying out whether this problem also occurs if you run qemu with emulated vmware graphics (`-vga vmware`).

**Comment by Manish-Kala-Jaat** [comment]
Yeah the repository is up to date

**Comment by Manish-Kala-Jaat** [comment]
also I tried the -vga vmware option but still the problem persists

**Comment by qookei** [comment]
The missing ioctl is DRM_IOCTL_MODE_CURSOR, which means that your build of managarm is older than 199ddd60841eeb6e118cd6f7046832aa5b8cbb62. Could you please run `xbstrap install managarm-system --rebuild` and `mkimage` even if your repository is up to date and tell us if the issue still happens

**Comment by avdgrinten** [comment]
Specifically, the `managarm/` repo needs to be up to date (not only the bootstrap-managarm one).

**Comment by avdgrinten** [comment]
@Manish-Kala-Jaat Does the nightly managarm image work for you?

**Comment by avdgrinten** [comment]
Closing the issue since this bug cannot be reproduced.
