### ISSUE TITLE
Port rustc to enable Rust drivers on managarm

### ISSUE THREAD

**Issue by avdgrinten** [managarm/managarm#91]
Rust is gaining a lot of popularity as a systems programming language. In managarm, Rust could be used for safety-critical user space drivers.

Note that the goal is to provide new functionality; it is not a goal to rewrite existing code in Rust. Since drivers in managarm are well-isolated anyway, Rust drivers can coexist with existing C++ code and communicate over existing IPC mechanisms.

**Comment by PenetratingShot** [comment]
yes do it

**Comment by avdgrinten** [comment]
Further progress is tracked in https://github.com/orgs/managarm/projects/3.
